<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SoalQrSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tsoalqr')->insert([
            [
                'id' => 1,
                'level' => '1',
                'pertanyaan' => 'Nilai \\( x \\) yang memenuhi \\( 2x - 5 < 3x + 2 \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( x > -7 \\)',
                'option_2' => '\\( x < -7 \\)',
                'option_3' => '\\( x > 7 \\)',
                'option_4' => '\\( x < 7 \\)',
                'jawaban_benar' => 'x>-7',
                'gambar_soal' => null
            ],
            [
                'id' => 2,
                'level' => '1',
                'pertanyaan' => 'Jika \\( x + y = 7 \\) dan \\( 2x - y = 5 \\), maka nilai \\( y \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '3',
                'gambar_soal' => null
            ],
            [
                'id' => 3,
                'level' => '1',
                'pertanyaan' => 'Gradien garis yang melalui titik \\( (1, 2) \\) dan \\( (3, 12) \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '5',
                'gambar_soal' => null
            ],
            [
                'id' => 4,
                'level' => '1',
                'pertanyaan' => 'Nilai \\( x \\) yang memenuhi \\( 2^{x+1} = 16 \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '3',
                'gambar_soal' => null
            ],
            [
                'id' => 5,
                'level' => '1',
                'pertanyaan' => 'Median dari data: 3, 5, 7, 8, 10 adalah...',
                'reward_amount'=> 1200,
                'option_1' => '3',
                'option_2' => '5,5',
                'option_3' => '7',
                'option_4' => '7,5',
                'jawaban_benar' => '7',
                'gambar_soal' => null
            ],
            [
                'id' => 6,
                'level' => '1',
                'pertanyaan' => 'Jika \\( \\tan \\theta = 1 \\), maka \\( \\theta \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( 30^\\circ \\)',
                'option_2' => '\\( 45^\\circ \\)',
                'option_3' => '\\( 60^\\circ \\)',
                'option_4' => '\\( 90^\\circ \\)',
                'jawaban_benar' => '45∘',
                'gambar_soal' => null
            ],
            [
                'id' => 7,
                'level' => '1',
                'pertanyaan' => 'Titik puncak parabola \\( y = x^2 - 4x + 3 \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( (2, -1) \\)',
                'option_2' => '\\( (1, 0) \\)',
                'option_3' => '\\( (-2, 15) \\)',
                'option_4' => '\\( (4, 3) \\)',
                'jawaban_benar' => '(2,-1)',
                'gambar_soal' => null
            ],
            [
                'id' => 8,
                'level' => '1',
                'pertanyaan' => 'Jika \\( f(x) = x^3 + 4x^2 - 2x - 3 \\), maka \\( f(5) \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '212',
                'gambar_soal' => null
            ],
            [
                'id' => 9,
                'level' => '1',
                'pertanyaan' => 'Negasi dari "Semua siswa rajin belajar" adalah...',
                'reward_amount'=> 1200,
                'option_1' => 'Beberapa siswa tidak rajin belajar',
                'option_2' => 'Tidak ada siswa yang rajin belajar',
                'option_3' => 'Semua siswa tidak rajin belajar',
                'option_4' => 'Beberapa siswa rajin belajar',
                'jawaban_benar' => 'Beberapa siswa tidak rajin belajar',
                'gambar_soal' => null
            ],
            [
                'id' => 10,
                'level' => '1',
                'pertanyaan' => 'Jika \\( p \\) benar dan \\( q \\) salah, nilai kebenaran \\( p \\lor \\lnot q \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => 'Benar',
                'option_2' => 'Salah',
                'option_3' => 'Tidak dapat ditentukan',
                'option_4' => 'Bukan pernyataan',
                'jawaban_benar' => 'Benar',
                'gambar_soal' => null
            ],
            [
                'id' => 11,
                'level' => '1',
                'pertanyaan' => 'Gradien garis \\( y = -2x + 5 \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '-2',
                'gambar_soal' => null
            ],
            [
                'id' => 12,
                'level' => '1',
                'pertanyaan' => '\\( \\mathrm{HCl} \\) termasuk senyawa...',
                'reward_amount'=> 1200,
                'option_1' => 'Basa kuat',
                'option_2' => 'Asam kuat',
                'option_3' => 'Garam',
                'option_4' => 'Netral',
                'jawaban_benar' => 'Asam kuat',
                'gambar_soal' => null
            ],
            [
                'id' => 13,
                'level' => '1',
                'pertanyaan' => 'Unsur \\( X \\) memiliki nomor atom \\( 11 \\) dan massa atom \\( 23 \\). Maka jumlah neutronnya adalah...',
                'reward_amount'=> 1200,
                'option_1' => '12',
                'option_2' => '11',
                'option_3' => '23',
                'option_4' => '13',
                'jawaban_benar' => '12',
                'gambar_soal' => null
            ],
            [
                'id' => 14,
                'level' => '1',
                'pertanyaan' => 'Rumus kimia dari air adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( \\mathrm{CO_2} \\)',
                'option_2' => '\\( \\mathrm{H_2O} \\)',
                'option_3' => '\\( \\mathrm{HCl} \\)',
                'option_4' => '\\( \\mathrm{OH^-} \\)',
                'jawaban_benar' => 'h2o',
                'gambar_soal' => null
            ],
            [
                'id' => 15,
                'level' => '1',
                'pertanyaan' => 'Rumus massa jenis adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( m \\times V \\)',
                'option_2' => '\\( \\frac{V}{m} \\)',
                'option_3' => '\\( \\frac{m}{V} \\)',
                'option_4' => '\\( V \\times m^2 \\)',
                'jawaban_benar' => 'mv',
                'gambar_soal' => null
            ],
            [
                'id' => 16,
                'level' => '1',
                'pertanyaan' => 'Asam memiliki pH...',
                'reward_amount'=> 1200,
                'option_1' => 'Di atas 7',
                'option_2' => 'Tepat 7',
                'option_3' => 'Di bawah 7',
                'option_4' => 'Tidak terukur',
                'jawaban_benar' => 'Di bawah 7',
                'gambar_soal' => null
            ],
            [
                'id' => 17,
                'level' => '2',
                'pertanyaan' => 'Berapa digit terakhir dari \\( 33^{2025} \\)?',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '3',
                'gambar_soal' => null
            ],
            [
                'id' => 18,
                'level' => '2',
                'pertanyaan' => 'Nilai dari \\( \\sin 150^\\circ + \\cos 300^\\circ \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '1',
                'gambar_soal' => null
            ],
            [
                'id' => 19,
                'level' => '2',
                'pertanyaan' => 'Persamaan garis yang melalui titik \\( (1, 2) \\) dengan gradien \\( 3 \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( y = 3x - 1 \\)',
                'option_2' => '\\( y = 3x + 1 \\)',
                'option_3' => '\\( y = x + 3 \\)',
                'option_4' => '\\( y = -3x + 5 \\)',
                'jawaban_benar' => 'y=3x-1',
                'gambar_soal' => null
            ],
            [
                'id' => 20,
                'level' => '2',
                'pertanyaan' => 'Turunan pertama dari \\( f(x) = 3x^4 - 2x^2 + 5 \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( 12x^3 - 4x \\)',
                'option_2' => '\\( 6x^3 - 2x \\)',
                'option_3' => '\\( 12x^2 - 4 \\)',
                'option_4' => '\\( 6x^3 - 4x \\)',
                'jawaban_benar' => '12x3-4x',
                'gambar_soal' => null
            ],
            [
                'id' => 21,
                'level' => '2',
                'pertanyaan' => 'Jika \\( f(x) = 2x - 1 \\) dan \\( g(x) = x^2 \\), maka \\( (f \\circ g)(3) \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '17',
                'gambar_soal' => null
            ],
            [
                'id' => 22,
                'level' => '2',
                'pertanyaan' => 'Jika diketahui \\( M_r\\ \\mathrm{H_2O} = 18 \\) dan massa \\( 36 \\) gram, maka jumlah mol \\( \\mathrm{H_2O} \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '1',
                'option_2' => '2',
                'option_3' => '3',
                'option_4' => '18',
                'jawaban_benar' => '2',
                'gambar_soal' => null
            ],
            [
                'id' => 23,
                'level' => '2',
                'pertanyaan' => 'Volume 2 mol gas ideal pada STP adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( 22{,}4\\ \\text{L} \\)',
                'option_2' => '\\( 24\\ \\text{L} \\)',
                'option_3' => '\\( 44{,}8\\ \\text{L} \\)',
                'option_4' => '\\( 48\\ \\text{L} \\)',
                'jawaban_benar' => '44,8 l',
                'gambar_soal' => null
            ],
            [
                'id' => 24,
                'level' => '2',
                'pertanyaan' => 'Jika \\( 25\\ \\mathrm{mL} \\) \\( \\mathrm{HCl} \\) \\( 0{,}1\\ \\mathrm{M} \\) direaksikan sempurna dengan \\( 25\\ \\mathrm{mL} \\) \\( \\mathrm{NaOH} \\) \\( 0{,}1\\ \\mathrm{M} \\), maka pH campuran setelah reaksi adalah...',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '7',
                'gambar_soal' => null
            ],
            [
                'id' => 25,
                'level' => '2',
                'pertanyaan' => 'Jika massa jenis larutan adalah \\( 1{,}2\\ \\mathrm{g/mL} \\) dan volumenya \\( 250\\ \\mathrm{mL} \\), hitung massanya dalam gram!',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '300',
                'gambar_soal' => null
            ],
            [
                'id' => 26,
                'level' => '2',
                'pertanyaan' => 'Ion yang terbentuk dari pelepasan elektron disebut...',
                'reward_amount'=> 1200,
                'option_1' => 'Anion',
                'option_2' => 'Kation',
                'option_3' => 'Proton',
                'option_4' => 'Elektron',
                'jawaban_benar' => 'Kation',
                'gambar_soal' => null
            ],
            [
                'id' => 27,
                'level' => '3',
                'pertanyaan' => 'Jika akar-akar persamaan \\( x^2 - 4x + 13 = 0 \\) adalah \\( \\alpha \\) dan \\( \\beta \\), nilai dari \\( \\alpha^4 + \\beta^4 \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '-238',
                'option_2' => '-100',
                'option_3' => '169',
                'option_4' => '338',
                'jawaban_benar' => '-238',
                'gambar_soal' => null
            ],
            [
                'id' => 28,
                'level' => '3',
                'pertanyaan' => 'Berapa sisa pembagian \\( 3^{100} \\) oleh \\( 101 \\)?',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '1',
                'gambar_soal' => null
            ],
            [
                'id' => 29,
                'level' => '3',
                'pertanyaan' => 'Sebuah pabrik memproduksi dua jenis tas: tas premium (Rp\\(500.000\\)/unit) dan tas standar (Rp\\(300.000\\)/unit). Setiap tas premium membutuhkan \\(4\\) jam kerja dan \\(2\\) kg bahan baku, sedangkan tas standar membutuhkan \\(2\\) jam kerja dan \\(1\\) kg bahan baku. Jika tersedia \\(200\\) jam kerja dan \\(100\\) kg bahan baku per hari, berapa keuntungan maksimum yang dapat diperoleh?',
                'reward_amount'=> 1200,
                'option_1' => 'Rp25 juta',
                'option_2' => 'Rp30 juta',
                'option_3' => 'Rp35 juta',
                'option_4' => 'Rp40 juta',
                'jawaban_benar' => 'Rp30 juta',
                'gambar_soal' => null
            ],
            [
                'id' => 30,
                'level' => '3',
                'pertanyaan' => 'Populasi bakteri berkembang 2 kali lipat setiap 3 jam. Jika awalnya ada 100 bakteri, berapa waktu yang dibutuhkan untuk mencapai 6.400 bakteri ?',
                'reward_amount'=> 1200,
                'option_1' => '12 jam',
                'option_2' => '18 jam',
                'option_3' => '24 jam',
                'option_4' => '30 jam',
                'jawaban_benar' => '18 jam',
                'gambar_soal' => null
            ],
            [
                'id' => 31,
                'level' => '3',
                'pertanyaan' => 'Sebuah wadah terdiri dari tabung (jari-jari \\(7\\ \\text{cm}\\), tinggi \\(10\\ \\text{cm}\\)) dan kerucut (jari-jari \\(7\\ \\text{cm}\\), tinggi \\(24\\ \\text{cm}\\)) yang ditumpuk. Berapa volume total wadah (dalam \\(\\pi\\))?',
                'reward_amount'=> 1200,
                'option_1' => '\\( 392\\pi\\ \\mathrm{cm^3} \\)',
                'option_2' => '\\( 784\\pi\\ \\mathrm{cm^3} \\)',
                'option_3' => '\\( 882\\pi\\ \\mathrm{cm^3} \\)',
                'option_4' => '\\( 960\\pi\\ \\mathrm{cm^3} \\)',
                'jawaban_benar' => '882π cm3',
                'gambar_soal' => null
            ],
            [
                'id' => 32,
                'level' => '3',
                'pertanyaan' => 'Ion kompleks berikut yang memiliki bilangan koordinasi 6 adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( \\mathrm{[Ag(NH_3)_2]^+} \\)',
                'option_2' => '\\( \\mathrm{[Fe(CN)_6]^{3-}} \\)',
                'option_3' => '\\( \\mathrm{[Cu(NH_3)_4]^{2+}} \\)',
                'option_4' => '\\( \\mathrm{[Zn(OH)_4]^{2-}} \\)',
                'jawaban_benar' => '[fe(cn)6]3-',
                'gambar_soal' => null
            ],
            [
                'id' => 33,
                'level' => '3',
                'pertanyaan' => 'Hitung \\( \\Delta G \\) (kJ) jika \\( \\Delta H = -100\\ \\mathrm{kJ} \\) dan \\( \\Delta S = +200\\ \\mathrm{J/mol{\\cdot}K} \\) pada \\( 300\\ \\mathrm{K} \\)!',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '-160',
                'gambar_soal' => null
            ],
            [
                'id' => 34,
                'level' => '3',
                'pertanyaan' => 'Larutan \\( \\mathrm{CH_3COOH} \\) \\( 0{,}1\\ \\mathrm{M} \\) memiliki derajat ionisasi \\( \\alpha = 0{,}01 \\), hitung \\( [\\mathrm{H}^+] \\) larutan tersebut!',
                'reward_amount'=> 1200,
                'option_1' => '0,001 M',
                'option_2' => '0,01 M',
                'option_3' => '0,1 M',
                'option_4' => '1 M',
                'jawaban_benar' => '0,001 M',
                'gambar_soal' => null
            ],
            [
                'id' => 35,
                'level' => '3',
                'pertanyaan' => 'Reaksi pengendapan akan terjadi jika larutan \\( \\mathrm{AgNO_3} \\) dicampur dengan...',
                'reward_amount'=> 1200,
                'option_1' => '\\( \\mathrm{NaCl} \\)',
                'option_2' => '\\( \\mathrm{KNO_3} \\)',
                'option_3' => '\\( \\mathrm{KCl} \\)',
                'option_4' => '\\( \\mathrm{HNO_3} \\)',
                'jawaban_benar' => 'nacl',
                'gambar_soal' => null
            ],
            [
                'id' => 36,
                'level' => '3',
                'pertanyaan' => 'Bentuk molekul dari \\( \\mathrm{NH_3} \\) berdasarkan teori VSEPR adalah...',
                'reward_amount'=> 1200,
                'option_1' => 'Linear',
                'option_2' => 'Tetrahedral',
                'option_3' => 'Segitiga datar',
                'option_4' => 'Piramida trigonal',
                'jawaban_benar' => 'Piramida trigonal',
                'gambar_soal' => null
            ],
            [
                'id' => 37,
                'level' => '2',
                'pertanyaan' => 'Jika \\( f(x) = 3x - 2 \\), maka \\( f^{-1}(4) \\) adalah…',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '2',
                'gambar_soal' => null
            ],
            [
                'id' => 38,
                'level' => '2',
                'pertanyaan' => 'Dua dadu dilempar. Peluang muncul jumlah mata dadu 7 adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( \\frac{1}{2} \\)',
                'option_2' => '\\( \\frac{1}{6} \\)  ',
                'option_3' => '\\( \\frac{1}{12} \\)  ',
                'option_4' => '\\( \\frac{1}{36} \\)',
                'jawaban_benar' => '16',
                'gambar_soal' => null
            ],
            [
                'id' => 39,
                'level' => '2',
                'pertanyaan' => 'Nilai dari \\( \\lim_{x \\to 3} \\frac{x^2 - 9}{x - 3} \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '6',
                'gambar_soal' => null
            ],
            [
                'id' => 40,
                'level' => '2',
                'pertanyaan' => 'Nilai dari \\( \\lim_{x \\to 0} \\frac{\\sin x}{x} \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '0',
                'option_2' => '1',
                'option_3' => 'Tak hingga',
                'option_4' => 'Tak terdefinisi',
                'jawaban_benar' => '1',
                'gambar_soal' => null
            ],
            [
                'id' => 41,
                'level' => '2',
                'pertanyaan' => 'Luas daerah yang dibatasi \\( y = x^2 \\) dan \\( y = 2x \\) adalah…',
                'reward_amount'=> 1200,
                'option_1' => '\\( 4 \\)',
                'option_2' => '\\( \\frac{8}{3} \\)',
                'option_3' => '\\( \\frac{16}{3} \\)',
                'option_4' => '\\( \\frac{4}{3} \\)',
                'jawaban_benar' => '43',
                'gambar_soal' => null
            ],
            [
                'id' => 42,
                'level' => '2',
                'pertanyaan' => 'Berapa banyak cara duduk 6 orang di meja bundar jika 2 orang tertentu tidak boleh bersebelahan?',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '72',
                'gambar_soal' => null
            ],
            [
                'id' => 43,
                'level' => '2',
                'pertanyaan' => 'Dalam satu set kartu remi (52 kartu), diambil satu kartu secara acak. Berapa peluang kartu yang terambil adalah kartu berwarna merah atau merupakan kartu King?',
                'reward_amount'=> 1200,
                'option_1' => '\\( \\frac{1}{2} \\)',
                'option_2' => '\\( \\frac{7}{13} \\)',
                'option_3' => '\\( \\frac{15}{26} \\)',
                'option_4' => '\\( \\frac{11}{52} \\)',
                'jawaban_benar' => '713',
                'gambar_soal' => null
            ],
            [
                'id' => 44,
                'level' => '2',
                'pertanyaan' => 'Diberikan vektor \\( \\mathbf{a} = (1, 2, 3) \\) dan \\( \\mathbf{b} = (2, -1, 0) \\). Panjang proyeksi vektor \\( \\mathbf{a} \\) pada vektor \\( \\mathbf{b} \\) adalah…',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '0',
                'gambar_soal' => null
            ],
            [
                'id' => 45,
                'level' => '2',
                'pertanyaan' => 'Jika vektor \\( \\mathbf{a} = (2, -1) \\) dan vektor \\( \\mathbf{b} = (3, 4) \\), hasil dari vektor \\( 2\\mathbf{a} + \\mathbf{b} \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( (5, 3) \\)',
                'option_2' => '\\( (8, -1) \\)',
                'option_3' => '\\( (6, -4) \\)',
                'option_4' => '\\( (7, 2) \\)',
                'jawaban_benar' => '(7,2)',
                'gambar_soal' => null
            ],
            [
                'id' => 46,
                'level' => '3',
                'pertanyaan' => 'Di sebuah kelas, 60% siswa suka matematika dan 40% suka fisika. Jika 30% suka keduanya, berapa peluang siswa yang suka fisika juga suka matematika? (Gunakan tanda titik { . } sebagai pengganti koma)',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '0.75',
                'gambar_soal' => null
            ],
            [
                'id' => 47,
                'level' => '3',
                'pertanyaan' => 'Diberikan suatu trapesium \(ABCD\) dengan \( AB \; \text{sejajar} \; CD \). Misalkan titik \(P\) dan \(Q\) berturut-turut pada \(AD\) dan \(BC\) sedemikian sehingga\( PQ \; \text{sejajar} \; AB \) dan membagi trapesium menjadi dua bagian yang sama luasnya. Jika \(AB = 17\) dan \(CD = 7\), maka nilai \(PQ\) adalah...',
                'reward_amount'=> 3000,
                'option_1' => '10',
                'option_2' => '12',
                'option_3' => '13',
                'option_4' => '15',
                'jawaban_benar' => '13',
                'gambar_soal' => null
            ],
            [
                'id' => 48,
                'level' => '3',
                'pertanyaan' => 'Jika vektor \\( \\mathbf{a} = (2, -1) \\) dan vektor \\( \\mathbf{b} = (3, 4) \\), hasil dari vektor \\( 2\\mathbf{a} + \\mathbf{b} \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( (5, 3) \\)',
                'option_2' => '\\( (8, -1) \\)',
                'option_3' => '\\( (6, -4) \\)',
                'option_4' => '\\( (7, 2) \\)',
                'jawaban_benar' => '(7,2)',
                'gambar_soal' => null
            ],
            [
                'id' => 49,
                'level' => '3',
                'pertanyaan' => 'Jika vektor \\( \\mathbf{a} = (2, -1) \\) dan vektor \\( \\mathbf{b} = (3, 4) \\), hasil dari vektor \\( 2\\mathbf{a} + \\mathbf{b} \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( (5, 3) \\)',
                'option_2' => '\\( (8, -1) \\)',
                'option_3' => '\\( (6, -4) \\)',
                'option_4' => '\\( (7, 2) \\)',
                'jawaban_benar' => '(7,2)',
                'gambar_soal' => null
            ],
            [
                'id' => 50,
                'level' => '3',
                'pertanyaan' => 'Jika vektor \\( \\mathbf{a} = (2, -1) \\) dan vektor \\( \\mathbf{b} = (3, 4) \\), hasil dari vektor \\( 2\\mathbf{a} + \\mathbf{b} \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( (5, 3) \\)',
                'option_2' => '\\( (8, -1) \\)',
                'option_3' => '\\( (6, -4) \\)',
                'option_4' => '\\( (7, 2) \\)',
                'jawaban_benar' => '(7,2)',
                'gambar_soal' => null
            ],
            [
                'id' => 51,
                'level' => '3',
                'pertanyaan' => 'Jika vektor \\( \\mathbf{a} = (2, -1) \\) dan vektor \\( \\mathbf{b} = (3, 4) \\), hasil dari vektor \\( 2\\mathbf{a} + \\mathbf{b} \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( (5, 3) \\)',
                'option_2' => '\\( (8, -1) \\)',
                'option_3' => '\\( (6, -4) \\)',
                'option_4' => '\\( (7, 2) \\)',
                'jawaban_benar' => '(7,2)',
                'gambar_soal' => null
            ],
        ]);
    }
}