<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SoalQrSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tsoalqr')->insert([
            [
                'id' => 1,
                'level' => '1',
                'pertanyaan' => 'Nilai \\( x \\) yang memenuhi \\( 2x - 5 < 3x + 2 \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( x > -7 \\)',
                'option_2' => '\\( x < -7 \\)',
                'option_3' => '\\( x > 7 \\)',
                'option_4' => '\\( x < 7 \\)',
                'jawaban_benar' => 'x>-7',
                'gambar_soal' => null
            ],
            [
                'id' => 2,
                'level' => '1',
                'pertanyaan' => 'Jika \\( x + y = 7 \\) dan \\( 2x - y = 5 \\), maka nilai \\( y \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '3',
                'gambar_soal' => null
            ],
            [
                'id' => 3,
                'level' => '1',
                'pertanyaan' => 'Gradien garis yang melalui titik \\( (1, 2) \\) dan \\( (3, 12) \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '5',
                'gambar_soal' => null
            ],
            [
                'id' => 4,
                'level' => '1',
                'pertanyaan' => 'Nilai \\( x \\) yang memenuhi \\( 2^{x+1} = 16 \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '3',
                'gambar_soal' => null
            ],
            [
                'id' => 5,
                'level' => '1',
                'pertanyaan' => 'Median dari data: 3, 5, 7, 8, 10 adalah...',
                'reward_amount'=> 1200,
                'option_1' => '3',
                'option_2' => '5,5',
                'option_3' => '7',
                'option_4' => '7,5',
                'jawaban_benar' => '7',
                'gambar_soal' => null
            ],
            [
                'id' => 6,
                'level' => '1',
                'pertanyaan' => 'Jika \\( \\tan \\theta = 1 \\), maka \\( \\theta \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( 30^\\circ \\)',
                'option_2' => '\\( 45^\\circ \\)',
                'option_3' => '\\( 60^\\circ \\)',
                'option_4' => '\\( 90^\\circ \\)',
                'jawaban_benar' => '45∘',
                'gambar_soal' => null
            ],
            [
                'id' => 7,
                'level' => '1',
                'pertanyaan' => 'Titik puncak parabola \\( y = x^2 - 4x + 3 \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( (2, -1) \\)',
                'option_2' => '\\( (1, 0) \\)',
                'option_3' => '\\( (-2, 15) \\)',
                'option_4' => '\\( (4, 3) \\)',
                'jawaban_benar' => '(2,-1)',
                'gambar_soal' => null
            ],
            [
                'id' => 8,
                'level' => '1',
                'pertanyaan' => 'Jika \\( f(x) = x^3 + 4x^2 - 2x - 3 \\), maka \\( f(5) \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '212',
                'gambar_soal' => null
            ],
            [
                'id' => 9,
                'level' => '1',
                'pertanyaan' => 'Negasi dari "Semua siswa rajin belajar" adalah...',
                'reward_amount'=> 1200,
                'option_1' => 'Beberapa siswa tidak rajin belajar',
                'option_2' => 'Tidak ada siswa yang rajin belajar',
                'option_3' => 'Semua siswa tidak rajin belajar',
                'option_4' => 'Beberapa siswa rajin belajar',
                'jawaban_benar' => 'Beberapa siswa tidak rajin belajar',
                'gambar_soal' => null
            ],
            [
                'id' => 10,
                'level' => '1',
                'pertanyaan' => 'Jika \\( p \\) benar dan \\( q \\) salah, nilai kebenaran \\( p \\lor \\lnot q \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => 'Benar',
                'option_2' => 'Salah',
                'option_3' => 'Tidak dapat ditentukan',
                'option_4' => 'Bukan pernyataan',
                'jawaban_benar' => 'Benar',
                'gambar_soal' => null
            ],
            [
                'id' => 11,
                'level' => '1',
                'pertanyaan' => 'Gradien garis \\( y = -2x + 5 \\) adalah...',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '-2',
                'gambar_soal' => null
            ],
            [
                'id' => 12,
                'level' => '1',
                'pertanyaan' => '\\( \\mathrm{HCl} \\) termasuk senyawa...',
                'reward_amount'=> 1200,
                'option_1' => 'Basa kuat',
                'option_2' => 'Asam kuat',
                'option_3' => 'Garam',
                'option_4' => 'Netral',
                'jawaban_benar' => 'Asam kuat',
                'gambar_soal' => null
            ],
            [
                'id' => 13,
                'level' => '1',
                'pertanyaan' => 'Unsur \\( X \\) memiliki nomor atom \\( 11 \\) dan massa atom \\( 23 \\). Maka jumlah neutronnya adalah...',
                'reward_amount'=> 1200,
                'option_1' => '12',
                'option_2' => '11',
                'option_3' => '23',
                'option_4' => '13',
                'jawaban_benar' => '12',
                'gambar_soal' => null
            ],
            [
                'id' => 14,
                'level' => '1',
                'pertanyaan' => 'Rumus kimia dari air adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( \\mathrm{CO_2} \\)',
                'option_2' => '\\( \\mathrm{H_2O} \\)',
                'option_3' => '\\( \\mathrm{HCl} \\)',
                'option_4' => '\\( \\mathrm{OH^-} \\)',
                'jawaban_benar' => 'h2o',
                'gambar_soal' => null
            ],
            [
                'id' => 15,
                'level' => '1',
                'pertanyaan' => 'Rumus massa jenis adalah...',
                'reward_amount'=> 1200,
                'option_1' => '\\( m \\times V \\)',
                'option_2' => '\\( \\frac{V}{m} \\)',
                'option_3' => '\\( \\frac{m}{V} \\)',
                'option_4' => '\\( V \\times m^2 \\)',
                'jawaban_benar' => 'mv',
                'gambar_soal' => null
            ],
            [
                'id' => 16,
                'level' => '1',
                'pertanyaan' => 'Asam memiliki pH...',
                'reward_amount'=> 1200,
                'option_1' => 'Di atas 7',
                'option_2' => 'Tepat 7',
                'option_3' => 'Di bawah 7',
                'option_4' => 'Tidak terukur',
                'jawaban_benar' => 'Di bawah 7',
                'gambar_soal' => null
            ],
            [
                'id' => 17,
                'level' => '2',
                'pertanyaan' => 'Berapa digit terakhir dari \\( 33^{2025} \\)?',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '3',
                'gambar_soal' => null
            ],
            [
                'id' => 18,
                'level' => '2',
                'pertanyaan' => 'Nilai dari \\( \\sin 150^\\circ + \\cos 300^\\circ \\) adalah...',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '1',
                'gambar_soal' => null
            ],
            [
                'id' => 19,
                'level' => '2',
                'pertanyaan' => 'Persamaan garis yang melalui titik \\( (1, 2) \\) dengan gradien \\( 3 \\) adalah...',
                'reward_amount'=> 2000,
                'option_1' => '\\( y = 3x - 1 \\)',
                'option_2' => '\\( y = 3x + 1 \\)',
                'option_3' => '\\( y = x + 3 \\)',
                'option_4' => '\\( y = -3x + 5 \\)',
                'jawaban_benar' => 'y=3x-1',
                'gambar_soal' => null
            ],
            [
                'id' => 20,
                'level' => '2',
                'pertanyaan' => 'Turunan pertama dari \\( f(x) = 3x^4 - 2x^2 + 5 \\) adalah...',
                'reward_amount'=> 2000,
                'option_1' => '\\( 12x^3 - 4x \\)',
                'option_2' => '\\( 6x^3 - 2x \\)',
                'option_3' => '\\( 12x^2 - 4 \\)',
                'option_4' => '\\( 6x^3 - 4x \\)',
                'jawaban_benar' => '12x3-4x',
                'gambar_soal' => null
            ],
            [
                'id' => 21,
                'level' => '2',
                'pertanyaan' => 'Jika \\( f(x) = 2x - 1 \\) dan \\( g(x) = x^2 \\), maka \\( (f \\circ g)(3) \\) adalah...',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '17',
                'gambar_soal' => null
            ],
            [
                'id' => 22,
                'level' => '2',
                'pertanyaan' => 'Jika diketahui \\( M_r\\ \\mathrm{H_2O} = 18 \\) dan massa \\( 36 \\) gram, maka jumlah mol \\( \\mathrm{H_2O} \\) adalah...',
                'reward_amount'=> 2000,
                'option_1' => '1',
                'option_2' => '2',
                'option_3' => '3',
                'option_4' => '18',
                'jawaban_benar' => '2',
                'gambar_soal' => null
            ],
            [
                'id' => 23,
                'level' => '2',
                'pertanyaan' => 'Volume 2 mol gas ideal pada STP adalah...',
                'reward_amount'=> 2000,
                'option_1' => '\\( 22{,}4\\ \\text{L} \\)',
                'option_2' => '\\( 24\\ \\text{L} \\)',
                'option_3' => '\\( 44{,}8\\ \\text{L} \\)',
                'option_4' => '\\( 48\\ \\text{L} \\)',
                'jawaban_benar' => '44,8 l',
                'gambar_soal' => null
            ],
            [
                'id' => 24,
                'level' => '2',
                'pertanyaan' => 'Jika \\( 25\\ \\mathrm{mL} \\) \\( \\mathrm{HCl} \\) \\( 0{,}1\\ \\mathrm{M} \\) direaksikan sempurna dengan \\( 25\\ \\mathrm{mL} \\) \\( \\mathrm{NaOH} \\) \\( 0{,}1\\ \\mathrm{M} \\), maka pH campuran setelah reaksi adalah...',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '7',
                'gambar_soal' => null
            ],
            [
                'id' => 25,
                'level' => '2',
                'pertanyaan' => 'Jika massa jenis larutan adalah \\( 1{,}2\\ \\mathrm{g/mL} \\) dan volumenya \\( 250\\ \\mathrm{mL} \\), hitung massanya dalam gram!',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '300',
                'gambar_soal' => null
            ],
            [
                'id' => 26,
                'level' => '2',
                'pertanyaan' => 'Ion yang terbentuk dari pelepasan elektron disebut...',
                'reward_amount'=> 2000,
                'option_1' => 'Anion',
                'option_2' => 'Kation',
                'option_3' => 'Proton',
                'option_4' => 'Elektron',
                'jawaban_benar' => 'Kation',
                'gambar_soal' => null
            ],
            [
                'id' => 27,
                'level' => '3',
                'pertanyaan' => 'Jika akar-akar persamaan \\( x^2 - 4x + 13 = 0 \\) adalah \\( \\alpha \\) dan \\( \\beta \\), nilai dari \\( \\alpha^4 + \\beta^4 \\) adalah...',
                'reward_amount'=> 3000,
                'option_1' => '-238',
                'option_2' => '-100',
                'option_3' => '169',
                'option_4' => '338',
                'jawaban_benar' => '-238',
                'gambar_soal' => null
            ],
            [
                'id' => 28,
                'level' => '3',
                'pertanyaan' => 'Berapa sisa pembagian \\( 3^{100} \\) oleh \\( 101 \\)?',
                'reward_amount'=> 3000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '1',
                'gambar_soal' => null
            ],
            [
                'id' => 29,
                'level' => '3',
                'pertanyaan' => 'Sebuah pabrik memproduksi dua jenis tas: tas premium (Rp\\(500.000\\)/unit) dan tas standar (Rp\\(300.000\\)/unit). Setiap tas premium membutuhkan \\(4\\) jam kerja dan \\(2\\) kg bahan baku, sedangkan tas standar membutuhkan \\(2\\) jam kerja dan \\(1\\) kg bahan baku. Jika tersedia \\(200\\) jam kerja dan \\(100\\) kg bahan baku per hari, berapa keuntungan maksimum yang dapat diperoleh?',
                'reward_amount'=> 3000,
                'option_1' => 'Rp25 juta',
                'option_2' => 'Rp30 juta',
                'option_3' => 'Rp35 juta',
                'option_4' => 'Rp40 juta',
                'jawaban_benar' => 'Rp30 juta',
                'gambar_soal' => null
            ],
            [
                'id' => 30,
                'level' => '3',
                'pertanyaan' => 'Populasi bakteri berkembang 2 kali lipat setiap 3 jam. Jika awalnya ada 100 bakteri, berapa waktu yang dibutuhkan untuk mencapai 6.400 bakteri ?',
                'reward_amount'=> 3000,
                'option_1' => '12 jam',
                'option_2' => '18 jam',
                'option_3' => '24 jam',
                'option_4' => '30 jam',
                'jawaban_benar' => '18 jam',
                'gambar_soal' => null
            ],
            [
                'id' => 31,
                'level' => '3',
                'pertanyaan' => 'Sebuah wadah terdiri dari tabung (jari-jari \\(7\\ \\text{cm}\\), tinggi \\(10\\ \\text{cm}\\)) dan kerucut (jari-jari \\(7\\ \\text{cm}\\), tinggi \\(24\\ \\text{cm}\\)) yang ditumpuk. Berapa volume total wadah (dalam \\(\\pi\\))?',
                'reward_amount'=> 3000,
                'option_1' => '\\( 392\\pi\\ \\mathrm{cm^3} \\)',
                'option_2' => '\\( 784\\pi\\ \\mathrm{cm^3} \\)',
                'option_3' => '\\( 882\\pi\\ \\mathrm{cm^3} \\)',
                'option_4' => '\\( 960\\pi\\ \\mathrm{cm^3} \\)',
                'jawaban_benar' => '882π cm3',
                'gambar_soal' => null
            ],
            [
                'id' => 32,
                'level' => '3',
                'pertanyaan' => 'Ion kompleks berikut yang memiliki bilangan koordinasi 6 adalah...',
                'reward_amount'=> 3000,
                'option_1' => '\\( \\mathrm{[Ag(NH_3)_2]^+} \\)',
                'option_2' => '\\( \\mathrm{[Fe(CN)_6]^{3-}} \\)',
                'option_3' => '\\( \\mathrm{[Cu(NH_3)_4]^{2+}} \\)',
                'option_4' => '\\( \\mathrm{[Zn(OH)_4]^{2-}} \\)',
                'jawaban_benar' => '[fe(cn)6]3-',
                'gambar_soal' => null
            ],
            [
                'id' => 33,
                'level' => '3',
                'pertanyaan' => 'Hitung \\( \\Delta G \\) (kJ) jika \\( \\Delta H = -100\\ \\mathrm{kJ} \\) dan \\( \\Delta S = +200\\ \\mathrm{J/mol{\\cdot}K} \\) pada \\( 300\\ \\mathrm{K} \\)!',
                'reward_amount'=> 3000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '-160',
                'gambar_soal' => null
            ],
            [
                'id' => 34,
                'level' => '3',
                'pertanyaan' => 'Larutan \\( \\mathrm{CH_3COOH} \\) \\( 0{,}1\\ \\mathrm{M} \\) memiliki derajat ionisasi \\( \\alpha = 0{,}01 \\), hitung \\( [\\mathrm{H}^+] \\) larutan tersebut!',
                'reward_amount'=> 3000,
                'option_1' => '0,001 M',
                'option_2' => '0,01 M',
                'option_3' => '0,1 M',
                'option_4' => '1 M',
                'jawaban_benar' => '0,001 M',
                'gambar_soal' => null
            ],
            [
                'id' => 35,
                'level' => '3',
                'pertanyaan' => 'Reaksi pengendapan akan terjadi jika larutan \\( \\mathrm{AgNO_3} \\) dicampur dengan...',
                'reward_amount'=> 3000,
                'option_1' => '\\( \\mathrm{NaCl} \\)',
                'option_2' => '\\( \\mathrm{KNO_3} \\)',
                'option_3' => '\\( \\mathrm{KCl} \\)',
                'option_4' => '\\( \\mathrm{HNO_3} \\)',
                'jawaban_benar' => 'nacl',
                'gambar_soal' => null
            ],
            [
                'id' => 36,
                'level' => '3',
                'pertanyaan' => 'Bentuk molekul dari \\( \\mathrm{NH_3} \\) berdasarkan teori VSEPR adalah...',
                'reward_amount'=> 3000,
                'option_1' => 'Linear',
                'option_2' => 'Tetrahedral',
                'option_3' => 'Segitiga datar',
                'option_4' => 'Piramida trigonal',
                'jawaban_benar' => 'Piramida trigonal',
                'gambar_soal' => null
            ],
            [
                'id' => 37,
                'level' => '2',
                'pertanyaan' => 'Jika \\( f(x) = 3x - 2 \\), maka \\( f^{-1}(4) \\) adalah…',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '2',
                'gambar_soal' => null
            ],
            [
                'id' => 38,
                'level' => '2',
                'pertanyaan' => 'Dua dadu dilempar. Peluang muncul jumlah mata dadu 7 adalah...',
                'reward_amount'=> 2000,
                'option_1' => '\\( \\frac{1}{2} \\)',
                'option_2' => '\\( \\frac{1}{6} \\)  ',
                'option_3' => '\\( \\frac{1}{12} \\)  ',
                'option_4' => '\\( \\frac{1}{36} \\)',
                'jawaban_benar' => '16',
                'gambar_soal' => null
            ],
            [
                'id' => 39,
                'level' => '2',
                'pertanyaan' => 'Nilai dari \\( \\lim_{x \\to 3} \\frac{x^2 - 9}{x - 3} \\) adalah...',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '6',
                'gambar_soal' => null
            ],
            [
                'id' => 40,
                'level' => '2',
                'pertanyaan' => 'Nilai dari \\( \\lim_{x \\to 0} \\frac{\\sin x}{x} \\) adalah...',
                'reward_amount'=> 2000,
                'option_1' => '0',
                'option_2' => '1',
                'option_3' => 'Tak hingga',
                'option_4' => 'Tak terdefinisi',
                'jawaban_benar' => '1',
                'gambar_soal' => null
            ],
            [
                'id' => 41,
                'level' => '2',
                'pertanyaan' => 'Luas daerah yang dibatasi \\( y = x^2 \\) dan \\( y = 2x \\) adalah…',
                'reward_amount'=> 2000,
                'option_1' => '\\( 4 \\)',
                'option_2' => '\\( \\frac{8}{3} \\)',
                'option_3' => '\\( \\frac{16}{3} \\)',
                'option_4' => '\\( \\frac{4}{3} \\)',
                'jawaban_benar' => '43',
                'gambar_soal' => null
            ],
            [
                'id' => 42,
                'level' => '2',
                'pertanyaan' => 'Berapa banyak cara duduk 6 orang di meja bundar jika 2 orang tertentu tidak boleh bersebelahan?',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '72',
                'gambar_soal' => null
            ],
            [
                'id' => 43,
                'level' => '2',
                'pertanyaan' => 'Dalam satu set kartu remi (52 kartu), diambil satu kartu secara acak. Berapa peluang kartu yang terambil adalah kartu berwarna merah atau merupakan kartu King?',
                'reward_amount'=> 2000,
                'option_1' => '\\( \\frac{1}{2} \\)',
                'option_2' => '\\( \\frac{7}{13} \\)',
                'option_3' => '\\( \\frac{15}{26} \\)',
                'option_4' => '\\( \\frac{11}{52} \\)',
                'jawaban_benar' => '713',
                'gambar_soal' => null
            ],
            [
                'id' => 44,
                'level' => '2',
                'pertanyaan' => 'Diberikan vektor \\( \\mathbf{a} = (1, 2, 3) \\) dan \\( \\mathbf{b} = (2, -1, 0) \\). Panjang proyeksi vektor \\( \\mathbf{a} \\) pada vektor \\( \\mathbf{b} \\) adalah…',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '0',
                'gambar_soal' => null
            ],
            [
                'id' => 45,
                'level' => '2',
                'pertanyaan' => 'Jika vektor \\( \\mathbf{a} = (2, -1) \\) dan vektor \\( \\mathbf{b} = (3, 4) \\), hasil dari vektor \\( 2\\mathbf{a} + \\mathbf{b} \\) adalah...',
                'reward_amount'=> 2000,
                'option_1' => '\\( (5, 3) \\)',
                'option_2' => '\\( (8, -1) \\)',
                'option_3' => '\\( (6, -4) \\)',
                'option_4' => '\\( (7, 2) \\)',
                'jawaban_benar' => '(7,2)',
                'gambar_soal' => null
            ],
            [
                'id' => 46,
                'level' => '3',
                'pertanyaan' => 'Di sebuah kelas, 60% siswa suka matematika dan 40% suka fisika. Jika 30% suka keduanya, berapa peluang siswa yang suka fisika juga suka matematika? (Gunakan tanda titik { . } sebagai pengganti koma)',
                'reward_amount'=> 3000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '0.75',
                'gambar_soal' => null
            ],
            [
                'id' => 47,
                'level' => '3',
                'pertanyaan' => 'Diberikan suatu trapesium \(ABCD\) dengan \( AB \; \text{sejajar} \; CD \). Misalkan titik \(P\) dan \(Q\) berturut-turut pada \(AD\) dan \(BC\) sedemikian sehingga\( PQ \; \text{sejajar} \; AB \) dan membagi trapesium menjadi dua bagian yang sama luasnya. Jika \(AB = 17\) dan \(CD = 7\), maka nilai \(PQ\) adalah...',
                'reward_amount'=> 3000,
                'option_1' => '10',
                'option_2' => '12',
                'option_3' => '13',
                'option_4' => '15',
                'jawaban_benar' => '13',
                'gambar_soal' => null
            ],
            [
                'id' => 48,
                'level' => '3',
                'pertanyaan' => 'Sebuah roket bergerak dengan persamaan \( h(t) = -2t^2 + 40t \) (meter). Kapan roket mencapai ketinggian maksimum (dalam detik)?',
                'reward_amount'=> 3000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '10',
                'gambar_soal' => null
            ],
            [
                'id' => 49,
                'level' => '3',
                'pertanyaan' => 'Suatu perusahaan mengukur keuntungan \( U(t) = 2t \) dan biaya \( C(t) = t^2 + 4 \). Jika \( t \) adalah waktu dalam tahun, kapan keuntungan melebihi biaya untuk pertama kali?',
                'reward_amount'=> 3000,
                'option_1' => 'Tahun ke-3',
                'option_2' => 'Tahun ke-4',
                'option_3' => 'Tahun ke-5',
                'option_4' => 'Tahun ke-6',
                'jawaban_benar' => 'Tahun ke-5',
                'gambar_soal' => null
            ],
            [
                'id' => 50,
                'level' => '3',
                'pertanyaan' => 'Dari 10 siswa (4 perempuan: \( P_1, P_2, P_3, P_4 \) dan 6 laki-laki), sebuah tim berisi 5 orang dipilih secara acak. Berapa peluang tim itu terdiri dari tepat 2 perempuan dan \( P_1 \) dan \( P_2 \) tidak boleh bersama?',
                'reward_amount'=> 3000,
                'option_1' => '\( \frac{5}{21} \)',
                'option_2' => '\( \frac{10}{63} \)',
                'option_3' => '\( \frac{25}{63} \)',
                'option_4' => '\( \frac{50}{126} \)',
                'jawaban_benar' => '2563',
                'gambar_soal' => null
            ],
            [
                'id' => 51,
                'level' => '3',
                'pertanyaan' => 'Dari huruf-huruf dalam kata "KOMBINATORIKA", berapa banyak susunan berbeda yang bisa dibentuk jika semua huruf vokal tidak boleh saling berdampingan?',
                'reward_amount'=> 3000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '6350400',
                'gambar_soal' => null
            ],
            [
                'id' => 52,
                'level' => '1',
                'pertanyaan' => 'NaCl termasuk senyawa ionik.',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => 'TRUE',
                'gambar_soal' => null
            ],
            [
                'id' => 53,
                'level' => '1',
                'pertanyaan' => 'Semua senyawa karbon bersifat organik.',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => 'FALSE',
                'gambar_soal' => null
            ],
            [
                'id' => 54,
                'level' => '1',
                'pertanyaan' => 'Ion positif disebut anion.',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => 'FALSE',
                'gambar_soal' => null
            ],
            [
                'id' => 55,
                'level' => '1',
                'pertanyaan' => 'Air laut merupakan campuran heterogen.',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => 'FALSE',
                'gambar_soal' => null
            ],
            [
                'id' => 56,
                'level' => '1',
                'pertanyaan' => 'Elektrolit kuat menghantarkan listrik lebih baik daripada elektrolit lemah.',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => 'TRUE',
                'gambar_soal' => null
            ],
            [
                'id' => 57,
                'level' => '1',
                'pertanyaan' => 'Gas mulia bersifat sangat reaktif.',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => 'FALSE',
                'gambar_soal' => null
            ],
            [
                'id' => 58,
                'level' => '2',
                'pertanyaan' => 'Manakah pasangan volume dan konsentrasi berikut yang menghasilkan jumlah mol zat terbesar?',
                'reward_amount'=> 2000,
                'option_1' => '\(150\,\text{mL} \times 0{,}1\,\text{M}\)',
                'option_2' => '\(200\,\text{mL} \times 0{,}05\,\text{M}\)',
                'option_3' => '\(250\,\text{mL} \times 0{,}04\,\text{M}\)',
                'option_4' => '\(50\,\text{mL} \times 0{,}2\,\text{M}\)',
                'jawaban_benar' => '150ml×0,1m',
                'gambar_soal' => null
            ],
            [
                'id' => 59,
                'level' => '2',
                'pertanyaan' => 'Hitung konsentrasi larutan jika \(0{,}2\,\text{mol}\) zat terlarut dilarutkan dalam \(0{,}5\,\text{L}\) larutan! (Gunakan tanda titik { . } sebagai pengganti koma)',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '0.4',
                'gambar_soal' => null
            ],
            [
                'id' => 60,
                'level' => '2',
                'pertanyaan' => 'Jika \(25\,\text{mL}\) larutan \(\mathrm{HCl}\) \(1\,\text{M}\) diencerkan menjadi \(100\,\text{mL}\), berapa konsentrasi akhirnya? (Gunakan tanda titik { . } sebagai pengganti koma)',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '0.25',
                'gambar_soal' => null
            ],
            [
                'id' => 61,
                'level' => '2',
                'pertanyaan' => 'Berapa bilangan oksidasi N dalam \(\mathrm{HNO_3}\)?',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '+5',
                'gambar_soal' => null
            ],
            [
                'id' => 62,
                'level' => '2',
                'pertanyaan' => 'Jika volume larutan adalah \(0{,}25~\mathrm{L}\) dan konsentrasi \(1{,}5~\mathrm{M}\), berapa mol zat terlarutnya? (Gunakan tanda titik { . } sebagai pengganti koma)',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '0.375',
                'gambar_soal' => null
            ],
            [
                'id' => 63,
                'level' => '2',
                'pertanyaan' => 'Hitung jumlah mol elektron yang dibutuhkan untuk mereduksi \( 0{,}3 \) mol \( \mathrm{Fe}^{3+} \) menjadi \( \mathrm{Fe} \). (Gunakan tanda titik { . } sebagai pengganti koma)',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '0.9',
                'gambar_soal' => null
            ],
            [
                'id' => 64,
                'level' => '2',
                'pertanyaan' => 'Ion kompleks \( \left[\mathrm{Cu}(\mathrm{NH}_3)_4\right]^{2+} \) termasuk...',
                'reward_amount'=> 2000,
                'option_1' => 'Anion kompleks',
                'option_2' => 'Kation kompleks',
                'option_3' => 'Molekul nonpolar',
                'option_4' => 'Senyawa kovalen',
                'jawaban_benar' => 'Kation kompleks',
                'gambar_soal' => null
            ],
            [
                'id' => 65,
                'level' => '2',
                'pertanyaan' => 'Jika \( [\mathrm{H}^+] = 1 \times 10^{-6} \ \mathrm{M} \), hitung pH larutan tersebut!',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '6',
                'gambar_soal' => null
            ],
            [
                'id' => 66,
                'level' => '2',
                'pertanyaan' => 'Zat yang dapat menyebabkan efek Tyndall adalah...',
                'reward_amount'=> 2000,
                'option_1' => 'Larutan gula',
                'option_2' => 'Koloid susu',
                'option_3' => 'Air murni',
                'option_4' => 'Larutan NaCl',
                'jawaban_benar' => 'Koloid susu',
                'gambar_soal' => null
            ],
            [
                'id' => 67,
                'level' => '2',
                'pertanyaan' => 'Campuran \(200\ \mathrm{mL}\) NaOH \(0{,}1\ \mathrm{M}\) dengan \(100\ \mathrm{mL}\) HCl \(0{,}1\ \mathrm{M}\) akan menghasilkan larutan dengan pH…',
                'reward_amount'=> 2000,
                'option_1' => '1.9',
                'option_2' => '7.3',
                'option_3' => '11.2',
                'option_4' => '12.5',
                'jawaban_benar' => '12.5',
                'gambar_soal' => null
            ],
            [
                'id' => 68,
                'level' => '3',
                'pertanyaan' => 'Dalam reaksi pembakaran sempurna etana \((\mathrm{C_2H_6})\), jumlah mol \(\mathrm{CO_2}\) yang dihasilkan dari \(2\ \text{mol}\ \mathrm{C_2H_6}\) adalah...',
                'reward_amount'=> 3000,
                'option_1' => '2',
                'option_2' => '3',
                'option_3' => '4',
                'option_4' => '5',
                'jawaban_benar' => '4',
                'gambar_soal' => null
            ],
            [
                'id' => 69,
                'level' => '3',
                'pertanyaan' => 'Jika tekanan dalam sistem kesetimbangan gas ditingkatkan, maka sistem akan bergeser ke arah...',
                'reward_amount'=> 3000,
                'option_1' => 'Yang memiliki jumlah mol gas lebih besar',
                'option_2' => 'Yang memiliki jumlah mol gas lebih kecil',
                'option_3' => 'Tidak berubah',
                'option_4' => 'Endoterm',
                'jawaban_benar' => 'Yang memiliki jumlah mol gas lebih kecil',
                'gambar_soal' => null
            ],
            [
                'id' => 70,
                'level' => '3',
                'pertanyaan' => 'Sebanyak \( 0{,}1 \) mol \( \mathrm{Ca(OH)_2} \) dilarutkan dalam air hingga volumenya \( 1 \) liter. Hitung pH larutan!',
                'reward_amount'=> 3000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '13',
                'gambar_soal' => null
            ],
            [
                'id' => 71,
                'level' => '3',
                'pertanyaan' => 'Jika \( 0{,}02 \) mol \( \mathrm{CH_3COOH} \) \( 0{,}1 \, \mathrm{M} \) bereaksi dengan \( \mathrm{NaOH} \) \( 0{,}02 \) mol, maka pH larutan setelah reaksi adalah...',
                'reward_amount'=> 3000,
                'option_1' => '3',
                'option_2' => '4,7',
                'option_3' => '8,9',
                'option_4' => '13',
                'jawaban_benar' => '8,9',
                'gambar_soal' => null
            ],
            [
                'id' => 72,
                'level' => '3',
                'pertanyaan' => 'Hitung kalor (\( J \)) yang dilepaskan jika \( 100 \) gram air didinginkan dari \( 80^\circ\mathrm{C} \) ke \( 30^\circ\mathrm{C} \). \( (c = 4{,}18 \, \mathrm{J/g^\circ C}) \)',
                'reward_amount'=> 3000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '20900',
                'gambar_soal' => null
            ],
            [
                'id' => 73,
                'level' => '3',
                'pertanyaan' => 'Zat X memiliki titik didih lebih tinggi dari Y, padahal massa molarnya lebih kecil. Kemungkinan besar X memiliki...',
                'reward_amount'=> 3000,
                'option_1' => 'Ikatan ion',
                'option_2' => 'Ikatan hidrogen',
                'option_3' => 'Ikatan logam',
                'option_4' => 'Ikatan kovalen non-polar',
                'jawaban_benar' => 'Ikatan hidrogen',
                'gambar_soal' => null
            ],
            [
                'id' => 74,
                'level' => '1',
                'pertanyaan' => 'Jika tingkat akurasi produksi adalah \( 98\% \), dari \( 1000 \) unit yang diproduksi akan ada ... unit cacat.',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '20',
                'gambar_soal' => null
            ],
            [
                'id' => 75,
                'level' => '1',
                'pertanyaan' => 'Jika efisiensi lini produksi adalah \( 80\% \), waktu kerja efektif dalam \( 1 \) jam adalah ... menit.',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '48',
                'gambar_soal' => null
            ],
            [
                'id' => 76,
                'level' => '1',
                'pertanyaan' => 'Salah satu tujuan utama dari Teknik Industri adalah...',
                'reward_amount'=> 1200,
                'option_1' => 'Merancang desain bangunan',
                'option_2' => 'Mendesain produk',
                'option_3' => 'Mengoptimalkan sistem produksi',
                'option_4' => 'Mengoperasikan mesin',
                'jawaban_benar' => 'Mengoptimalkan sistem produksi',
                'gambar_soal' => null
            ],
            [
                'id' => 77,
                'level' => '1',
                'pertanyaan' => 'Tujuan utama dari \( \textit{Lean Manufacturing} \) adalah ...',
                'reward_amount'=> 1200,
                'option_1' => 'Menambah biaya',
                'option_2' => 'Mengurangi pemborosan',
                'option_3' => 'Menambah tenaga kerja',
                'option_4' => 'Memperbanyak produksi',
                'jawaban_benar' => 'Mengurangi pemborosan',
                'gambar_soal' => null
            ],
            [
                'id' => 78,
                'level' => '1',
                'pertanyaan' => 'Seorang operator dapat memproduksi pensil 50 unit dalam waktu 2 jam. produktivitas operator tersebut dalam memproduksi pensil adalah …. unit/jam.',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '25',
                'gambar_soal' => null
            ],
            [
                'id' => 79,
                'level' => '1',
                'pertanyaan' => 'Sebuah proses produksi membutuhkan 3 menit untuk memproduksi tiap unit. Berapa unit yang bisa diselesaikan dalam waktu 1 jam?',
                'reward_amount'=> 1200,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '20',
                'gambar_soal' => null
            ],
            [
                'id' => 80,
                'level' => '1',
                'pertanyaan' => 'Dalam \( \textit{SWOT} \), faktor \( \textit{Strength} \) merujuk pada ...',
                'reward_amount'=> 1200,
                'option_1' => 'Kelemahan yang harus diperbaiki',
                'option_2' => 'Ancaman dari pesaing',
                'option_3' => 'Keunggulan internal yang dimiliki perusahaan',
                'option_4' => 'Peluang dari luar perusahaan',
                'jawaban_benar' => 'Keunggulan internal yang dimiliki perusahaan',
                'gambar_soal' => null
            ],
            [
                'id' => 81,
                'level' => '1',
                'pertanyaan' => 'Faktor dalam ergonomi mencakup hal berikut, kecuali...',
                'reward_amount'=> 1200,
                'option_1' => 'Pencahayaan lingkungan kerja',
                'option_2' => 'Postur tubuh saat bekerja',
                'option_3' => 'Beban angkat dan aktivitas fisik',
                'option_4' => 'Struktur organisasi perusahaan',
                'jawaban_benar' => 'Struktur organisasi perusahaan',
                'gambar_soal' => null
            ],
            [
                'id' => 82,
                'level' => '1',
                'pertanyaan' => 'Aplikasi \( \textit{Aluminum Alloy} \), kecuali:',
                'reward_amount'=> 1200,
                'option_1' => 'Konstruksi Berat / Jembatan',
                'option_2' => 'Velg Mobil',
                'option_3' => 'Peralatan Dapur',
                'option_4' => 'Kemasan Minuman Kaleng',
                'jawaban_benar' => 'Konstruksi Berat / Jembatan',
                'gambar_soal' => null
            ],
            [
                'id' => 83,
                'level' => '1',
                'pertanyaan' => 'Manakah di bawah ini yang bukan termasuk kriteria utama dalam pemilihan lokasi fasilitas industri?',
                'reward_amount'=> 1200,
                'option_1' => 'Kedekatan dengan market',
                'option_2' => 'Biaya tenaga kerja',
                'option_3' => 'Jumlah pesaing',
                'option_4' => 'Estetika lokasi',
                'jawaban_benar' => 'Estetika lokasi',
                'gambar_soal' => null
            ],
            [
                'id' => 84,
                'level' => '1',
                'pertanyaan' => 'Pengujian tarik (\textit{tensile test}) digunakan untuk mengetahui sifat logam seperti...',
                'reward_amount'=> 1200,
                'option_1' => 'Tingkat kerapatan',
                'option_2' => 'Titik leleh dan titik didih',
                'option_3' => 'Modulus elastisitas dan regangan',
                'option_4' => 'Kecepatan reaksi dengan udara',
                'jawaban_benar' => 'Modulus elastisitas dan regangan',
                'gambar_soal' => null
            ],
            [
                'id' => 85,
                'level' => '1',
                'pertanyaan' => 'Apa yang dimaksud dengan \( \textit{Delivery Lead Time} \)?',
                'reward_amount'=> 1200,
                'option_1' => 'Waktu yang dibutuhkan untuk menyelesaikan proses produksi',
                'option_2' => 'Waktu dari pesanan diterima hingga produk dikirim ke pelanggan',
                'option_3' => 'Waktu istirahat dalam proses distribusi',
                'option_4' => 'Total waktu kerja karyawan logistik',
                'jawaban_benar' => 'Waktu dari pesanan diterima hingga produk dikirim ke pelanggan',
                'gambar_soal' => null
            ],
            [
                'id' => 86,
                'level' => '1',
                'pertanyaan' => 'Jika sebuah perusahaan memiliki \( \textit{Delivery Lead Time} = 7 \) hari, artinya...',
                'reward_amount'=> 1200,
                'option_1' => 'Pelanggan menerima barang 7 hari setelah pemesanan',
                'option_2' => 'Barang diproduksi dalam 7 hari',
                'option_3' => 'Gudang diisi kembali setiap 7 hari',
                'option_4' => 'Pekerja Gudang harus bekerja 7 hari penuh',
                'jawaban_benar' => 'Pelanggan menerima barang 7 hari setelah pemesanan',
                'gambar_soal' => null
            ],
            [
                'id' => 87,
                'level' => '1',
                'pertanyaan' => 'Apa yang dimaksud dengan pendekatan \( \textit{Integrated System Thinking} \)?',
                'reward_amount'=> 1200,
                'option_1' => 'Pendekatan untuk membuat sistem menjadi lebih rumit tanpa mempertimbangkan keterkaitannya',
                'option_2' => 'Pemikiran parsial (hanya melihat sebagian kecil saja) dari suatu sistem',
                'option_3' => 'Pendekatan yang mempertimbangkan semua komponen sistem sebagai bagian yang saling terhubung',
                'option_4' => 'Pengujian sistem berdasarkan intuisi tanpa disertai analisis sistemastis terhadap suatu sistem',
                'jawaban_benar' => 'Pendekatan yang mempertimbangkan semua komponen sistem sebagai bagian yang saling terhubung',
                'gambar_soal' => null
            ],
            [
                'id' => 88,
                'level' => '1',
                'pertanyaan' => 'Berikut ini merupakan prinsip dasar manajemen mutu menurut \( \textit{ISO 9001} \), kecuali...',
                'reward_amount'=> 1200,
                'option_1' => 'Fokus pada pelanggan',
                'option_2' => 'Kepemimpinan',
                'option_3' => 'Pendekatan proses',
                'option_4' => 'Kompetisi antar karyawan',
                'jawaban_benar' => 'Kompetisi antar karyawan',
                'gambar_soal' => null
            ],
            [
                'id' => 89,
                'level' => '2',
                'pertanyaan' => 'Sistem \( \textit{JIT (Just in Time)} \) bertujuan untuk ...',
                'reward_amount'=> 2000,
                'option_1' => 'Memperbanyak kapasitas gudang',
                'option_2' => 'Mengurangi stok berlebih',
                'option_3' => 'Menunda pengiriman',
                'option_4' => 'Mengurangi jam lembur',
                'jawaban_benar' => 'Mengurangi stok berlebih',
                'gambar_soal' => null
            ],
            [
                'id' => 90,
                'level' => '2',
                'pertanyaan' => 'Sistem produksi yang dilakukan dalam satu alur tanpa gangguan disebut...',
                'reward_amount'=> 2000,
                'option_1' => '\( \textit{Parallel system} \)  ',
                'option_2' => '\( \textit{Push system} \)',
                'option_3' => '\( \textit{Multi-line system} \)',
                'option_4' => '\( \textit{One-piece flow} \)',
                'jawaban_benar' => 'one-piece flow',
                'gambar_soal' => null
            ],
            [
                'id' => 91,
                'level' => '2',
                'pertanyaan' => 'Konsep \( \textit{mass customization} \) bertujuan untuk ...',
                'reward_amount'=> 2000,
                'option_1' => 'Personalisasi produk dalam volume besar ',
                'option_2' => 'Produksi satu model saja',
                'option_3' => 'Menekan biaya produksi serendah mungkin',
                'option_4' => 'Menyeragamkan semua produk',
                'jawaban_benar' => 'Personalisasi produk dalam volume besar ',
                'gambar_soal' => null
            ],
            [
                'id' => 92,
                'level' => '2',
                'pertanyaan' => 'Konsep \( \textit{"Fitting the Task to the Man"} \) dalam ergonomi berarti ...',
                'reward_amount'=> 2000,
                'option_1' => 'Manusia harus menggantikan mesin',
                'option_2' => 'Semua pekerjaan dapat dikerjakan manusia',
                'option_3' => 'Tugas disesuaikan dengan kemampuan manusia ',
                'option_4' => 'Pekerjaan tidak dapat dimodifikasi ',
                'jawaban_benar' => 'Tugas disesuaikan dengan kemampuan manusia ',
                'gambar_soal' => null
            ],
            [
                'id' => 93,
                'level' => '2',
                'pertanyaan' => 'Jika sebuah mesin rusak dan berhenti \( 2 \) jam dari \( 10 \) jam kerja, maka efektivitas mesin tersebut adalah ...%.',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '80',
                'gambar_soal' => null
            ],
            [
                'id' => 94,
                'level' => '2',
                'pertanyaan' => 'Analisis sistem terintegrasi bertujuan untuk...',
                'reward_amount'=> 2000,
                'option_1' => 'Mengoptimalkan satu bagian saja ',
                'option_2' => 'Mengurangi keterlibatan pengguna ',
                'option_3' => 'Meminimalkan kinerja tim',
                'option_4' => 'Menyelaraskan seluruh elemen sistem',
                'jawaban_benar' => 'Menyelaraskan seluruh elemen sistem',
                'gambar_soal' => null
            ],
            [
                'id' => 95,
                'level' => '2',
                'pertanyaan' => '\( \textit{Mass production} \) sangat erat kaitannya dengan konsep ...',
                'reward_amount'=> 2000,
                'option_1' => '\( \textit{Economic of scale} \) ',
                'option_2' => '\( \textit{Overproduction} \) ',
                'option_3' => '\( \textit{Batch system} \) ',
                'option_4' => '\( \textit{Lean thinking} \)',
                'jawaban_benar' => 'economic of scale',
                'gambar_soal' => null
            ],
            [
                'id' => 96,
                'level' => '2',
                'pertanyaan' => '\( \textit{Kaizen} \) dikenal sebagai budaya ...',
                'reward_amount'=> 2000,
                'option_1' => 'Penggantian sistem',
                'option_2' => 'Perbaikan berkelanjutan',
                'option_3' => 'Evaluasi tahunan',
                'option_4' => 'Perbaikan sebagian sistem saja',
                'jawaban_benar' => 'Perbaikan berkelanjutan',
                'gambar_soal' => null
            ],
            [
                'id' => 97,
                'level' => '2',
                'pertanyaan' => 'Mesin A menghasilkan \( 500 \) unit dalam \( 10 \) jam dan mesin B menghasilkan \( 300 \) unit dalam \( 5 \) jam. Mesin yang lebih produktif adalah ...',
                'reward_amount'=> 2000,
                'option_1' => 'Mesin A',
                'option_2' => 'Mesin B',
                'option_3' => 'Kedua mesin sama-sama produktif',
                'option_4' => 'Tergantung operator',
                'jawaban_benar' => 'Mesin B',
                'gambar_soal' => null
            ],
            [
                'id' => 98,
                'level' => '2',
                'pertanyaan' => 'Manfaat dilakukannya \( \textit{elemental breakdown} \) adalah ...',
                'reward_amount'=> 2000,
                'option_1' => 'Menggabung beberapa aktivitas menjadi satu tahapan besar',
                'option_2' => 'Menambah tahapan proses dalam rangkaian aktivitas',
                'option_3' => 'Menyusun ulang suatu aktivitas untuk efisiensi',
                'option_4' => 'Mengidentifikasi bagian proses paling cepat dalam rangkaian aktivitas',
                'jawaban_benar' => 'Menyusun ulang suatu aktivitas untuk efisiensi',
                'gambar_soal' => null
            ],
            [
                'id' => 99,
                'level' => '2',
                'pertanyaan' => 'Dalam sistem produksi, istilah \( \textit{lead time} \) merujuk pada ...',
                'reward_amount'=> 2000,
                'option_1' => 'Waktu akhir suatu proses produksi',
                'option_2' => 'Waktu mulai dari suatu proses produksi ',
                'option_3' => 'Waktu antara awal hingga akhir proses produksi',
                'option_4' => 'Volume produksi yang dihasilkan selama proses produksi berlangsung',
                'jawaban_benar' => 'Waktu antara awal hingga akhir proses produksi',
                'gambar_soal' => null
            ],
            [
                'id' => 100,
                'level' => '2',
                'pertanyaan' => 'Istilah \( \textit{dead stock} \) dalam industri artinya ...',
                'reward_amount'=> 2000,
                'option_1' => 'Barang yang dijual dengan harga yang sangat mahal',
                'option_2' => 'Barang yang cepat laku',
                'option_3' => 'Barang yang mudah rusak',
                'option_4' => 'Barang yang tidak terjual dalam waktu lama',
                'jawaban_benar' => 'Barang yang tidak terjual dalam waktu lama',
                'gambar_soal' => null
            ],
            [
                'id' => 101,
                'level' => '2',
                'pertanyaan' => 'Suatu mesin bekerja selama \( 8 \) jam dan menghasilkan \( 400 \) unit produk. Laju produksi dari mesin tersebut adalah ... unit/jam.',
                'reward_amount'=> 2000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '50',
                'gambar_soal' => null
            ],
            [
                'id' => 102,
                'level' => '2',
                'pertanyaan' => 'Tujuan dari \( \textit{system thinking} \) dalam Teknik Industri adalah ...',
                'reward_amount'=> 2000,
                'option_1' => 'Memahami interaksi antar elemen sistem',
                'option_2' => 'Memutuskan proses yang tidak penting dalam suatu sistem',
                'option_3' => 'Menghindari koordinasi antar elemen sistem',
                'option_4' => 'Fokus hanya pada output saja',
                'jawaban_benar' => 'Memahami interaksi antar elemen sistem',
                'gambar_soal' => null
            ],
            [
                'id' => 103,
                'level' => '2',
                'pertanyaan' => '\( \textit{Continuous improvement} \) mendorong suatu perusahaan untuk ...',
                'reward_amount'=> 2000,
                'option_1' => 'Berhenti pada saat suatu sistem dirasa sudah efisien ',
                'option_2' => 'Meningkatkan proses secara bertahap dan terus-menerus',
                'option_3' => 'Menambah tenaga kerja manual berdasarkan hasil evaluasi sistem',
                'option_4' => 'Menggunakan solusi lama untuk melanjutkan kinerja suatu sistem kedepannya',
                'jawaban_benar' => 'Meningkatkan proses secara bertahap dan terus-menerus',
                'gambar_soal' => null
            ],
            [
                'id' => 104,
                'level' => '2',
                'pertanyaan' => 'Dalam industri, efisiensi sistem yang tinggi berarti…',
                'reward_amount'=> 2000,
                'option_1' => 'Penggunaan bahan baku yang banyak dan variatif serta waktu produksi yang singkat',
                'option_2' => 'Penggunaan bahan baku yang sedikit dan waktu produksi yang lama',
                'option_3' => 'Jumlah tenaga kerja sesedikit mungkin dan output yang dihasilkan sedikit',
                'option_4' => 'Jumlah tenaga kerja sesedikit mungkin dan output yang dihasilkan banyak',
                'jawaban_benar' => 'Jumlah tenaga kerja sesedikit mungkin dan output yang dihasilkan banyak',
                'gambar_soal' => null
            ],
            [
                'id' => 105,
                'level' => '3',
                'pertanyaan' => 'Dalam besi tuang kelabu \( \textit{(grey cast iron)} \), struktur grafitnya berubah menjadi partikel.',
                'reward_amount'=> 3000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => 'FALSE',
                'gambar_soal' => null
            ],
            [
                'id' => 106,
                'level' => '3',
                'pertanyaan' => 'Elemen utama apa yang digunakan untuk membuat paduan \( \textit{stainless steel?} \)',
                'reward_amount'=> 3000,
                'option_1' => '\( \textit{Kromium} \) ',
                'option_2' => '\( \textit{Tin} \) ',
                'option_3' => '\( \textit{Titanium} \) ',
                'option_4' => '\( \textit{Aluminium} \)',
                'jawaban_benar' => 'kromium',
                'gambar_soal' => null
            ],
            [
                'id' => 107,
                'level' => '3',
                'pertanyaan' => 'Salah satu cara pemerintah menerapkan kebijakan fiskal ekspansif adalah dengan meningkatkan belanja pemerintah.',
                'reward_amount'=> 3000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => 'TRUE',
                'gambar_soal' => null
            ],
            [
                'id' => 108,
                'level' => '3',
                'pertanyaan' => 'Jika perekonomian suatu negara mengalami resesi, kebijakan moneter yang mungkin diambil oleh bank sentral untuk mendorong pertumbuhan adalah...',
                'reward_amount'=> 3000,
                'option_1' => 'Menaikkan suku bunga acuan',
                'option_2' => 'Menjual surat-surat berharga pemerintah',
                'option_3' => 'Menaikkan rasio cadangan wajib bank',
                'option_4' => 'Menurunkan suku bunga acuan',
                'jawaban_benar' => 'Menurunkan suku bunga acuan',
                'gambar_soal' => null
            ],
            [
                'id' => 109,
                'level' => '3',
                'pertanyaan' => 'Karyawan di PT ABC rata-rata membutuhkan waktu \( 3 \) menit untuk menyelesaikan satu produk. Base rate di PT ABC adalah Rp \( 6.000 \) per jamnya. Jika seorang karyawan dapat menyelesaikan \( 24 \) produk per jam, maka penghasilan (pokok dan insentif) yang bisa karyawan itu dapatkan jika dalam sehari terdapat \( 8 \) jam kerja adalah... rupiah.',
                'reward_amount'=> 3000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '57600',
                'gambar_soal' => null
            ],
            [
                'id' => 110,
                'level' => '3',
                'pertanyaan' => 'Produk Domestik Bruto (PDB) nominal suatu negara pada tahun \( 2024 \) adalah sebesar Rp\( 15.000 \) triliun. Indeks harga (deflator PDB) pada tahun \( 2024 \) adalah \( 125 \) (dengan tahun dasar \( 2015 = 100 \)). Maka nilai PDB riil (dalam triliun rupiah) pada tahun \( 2024 \) berdasarkan harga tahun dasar sebesar Rp... triliun.',
                'reward_amount'=> 3000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => '12000',
                'gambar_soal' => null
            ],
            [
                'id' => 111,
                'level' => '3',
                'pertanyaan' => 'Apa guna mesin frais \( \textit{Milling Machine} \)?',
                'reward_amount'=> 3000,
                'option_1' => 'Untuk membentuk permukaan material',
                'option_2' => 'Untuk menyambung material',
                'option_3' => 'Untuk mengecor besi',
                'option_4' => 'Untuk coating besi',
                'jawaban_benar' => 'Untuk membentuk permukaan material',
                'gambar_soal' => null
            ],
            [
                'id' => 112,
                'level' => '3',
                'pertanyaan' => 'Jenis las apa yang tidak memerlukan listrik sebagai energi?',
                'reward_amount'=> 3000,
                'option_1' => '\( \textit{GTAW} \)',
                'option_2' => '\( \textit{SMAW} \)',
                'option_3' => '\( \textit{Oxy-Acetylene Welding} \)',
                'option_4' => '\( \textit{Laser Beam Welding} \)',
                'jawaban_benar' => 'oxy-acetylene welding',
                'gambar_soal' => null
            ],
            [
                'id' => 113,
                'level' => '3',
                'pertanyaan' => 'Manakah dari pernyataan berikut yang sesuai dengan ilmu antropometri dalam ergonomi?',
                'reward_amount'=> 3000,
                'option_1' => 'Tingkat stress kerja karyawan',
                'option_2' => 'Pembuatan meja dan kursi yang sesuai dengan ukuran tubuh operator',
                'option_3' => 'Suhu dan kelembaban ruang kerja',
                'option_4' => 'Kapasitas dan output hasil produksi yang dapat diselesaikan oleh operator',
                'jawaban_benar' => 'Pembuatan meja dan kursi yang sesuai dengan ukuran tubuh operator',
                'gambar_soal' => null
            ],
            [
                'id' => 114,
                'level' => '3',
                'pertanyaan' => 'Optimalisasi tata letak dan desain ergonomis workstation dianggap sebagai variabel signifikan dalam meminimalkan pemborosan gerak serta meningkatkan efisiensi kognitif dan mekanis pekerja, sehingga berkontribusi terhadap peningkatan produktivitas kerja.',
                'reward_amount'=> 3000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => 'TRUE',
                'gambar_soal' => null
            ],
            [
                'id' => 115,
                'level' => '3',
                'pertanyaan' => 'Manakah elemen \( \textit{Therblig} \) yang sesuai untuk kegiatan mengambil bolpoin dari atas meja?',
                'reward_amount'=> 3000,
                'option_1' => 'RE, G, M',
                'option_2' => 'PP, P, A',
                'option_3' => 'PP, RL, U',
                'option_4' => 'AD, H, A',
                'jawaban_benar' => 'RE, G, M',
                'gambar_soal' => null
            ],
            [
                'id' => 116,
                'level' => '3',
                'pertanyaan' => 'PT Maju Terus adalah perusahaan manufaktur komponen otomotif. Dalam beberapa bulan terakhir, perusahaan mengalami peningkatan jumlah produk cacat, yaitu sekitar 10 dari setiap 1.000 unit yang diproduksi. Setelah dilakukan analisis, diketahui bahwa sebagian besar cacat disebabkan oleh kesalahan penyetelan mesin. Manajemen kemudian menerapkan pendekatan Kaizen dengan langkah-langkah berikut: Menyusun checklist penyetelan mesin harian. Memberikan pelatihan ulang kepada operator mesin. Menyediakan papan visual yang menunjukkan jumlah unit cacat per shift. Setelah satu bulan, jumlah produk cacat turun menjadi 3 dari setiap 1.000 unit. Manakah dari berikut ini yang merupakan prinsip Kaizen yang terlihat dalam studi kasus di atas?',
                'reward_amount'=> 3000,
                'option_1' => 'Fokus pada hasil akhir dan bonus karyawan',
                'option_2' => 'Perbaikan besar dengan investasi alat baru',
                'option_3' => 'Perubahan bertahap yang melibatkan karyawan',
                'option_4' => 'Restrukturisasi total organisasi',
                'jawaban_benar' => 'Perubahan bertahap yang melibatkan karyawan',
                'gambar_soal' => null
            ],
            [
                'id' => 117,
                'level' => '3',
                'pertanyaan' => 'Semakin tinggi struktur hirarki dalam suatu perusahaan, akan selalu membuat struktur organisasi dalam perusahaan tersebut semakin baik.',
                'reward_amount'=> 3000,
                'option_1' => null,
                'option_2' => null,
                'option_3' => null,
                'option_4' => null,
                'jawaban_benar' => 'FALSE',
                'gambar_soal' => null
            ],
            [
                'id' => 118,
                'level' => '3',
                'pertanyaan' => 'Waktu standar seorang pekerja untuk menyelesaikan perakitan handphone adalah \( 3 \) menit/unit-produk. Jika base rate sebesar Rp\( 5.000 \) per jamnya, maka berapa banyak uang yang didapat oleh seorang pekerja per jamnya jika dapat menghasilkan \( 22 \) unit per jamnya?',
                'reward_amount'=> 3000,
                'option_1' => '5.000 rupiah',
                'option_2' => '5.500 rupiah',
                'option_3' => '6.000 rupiah',
                'option_4' => '10.000 rupiah',
                'jawaban_benar' => '5.500 rupiah',
                'gambar_soal' => null
            ],
            [
                'id' => 119,
                'level' => '1',
                'pertanyaan' => 'Negara dengan ekspor teknologi tinggi terbesar di dunia adalah …',
                'reward_amount'=> 1200,
                'option_1' => 'Amerika',
                'option_2' => 'Jepang',
                'option_3' => 'China',
                'option_4' => 'Rusia',
                'jawaban_benar' => 'China',
                'gambar_soal' => null
            ],
            [
                'id' => 120,
                'level' => '1',
                'pertanyaan' => 'Satuan Internasional yang digunakan untuk mengukur berat adalah …',
                'reward_amount'=> 1200,
                'option_1' => 'Liter',
                'option_2' => 'Gram',
                'option_3' => 'Kilogram',
                'option_4' => 'Newton',
                'jawaban_benar' => 'Kilogram',
                'gambar_soal' => null
            ],
            [
                'id' => 121,
                'level' => '1',
                'pertanyaan' => 'Komponen yang menyimpan energi listrik dalam rangkaian disebut …',
                'reward_amount'=> 1200,
                'option_1' => 'Kapasitor',
                'option_2' => 'Resistor',
                'option_3' => 'Baterai',
                'option_4' => 'Generator',
                'jawaban_benar' => 'Kapasitor',
                'gambar_soal' => null
            ],
            [
                'id' => 122,
                'level' => '1',
                'pertanyaan' => 'Bahan bakar fosil terbentuk dari …',
                'reward_amount'=> 1200,
                'option_1' => 'Kelapa sawit',
                'option_2' => 'Sisa makhluk hidup purba',
                'option_3' => 'Kotoran hewan',
                'option_4' => 'Tumbuhan yang membusuk',
                'jawaban_benar' => 'Sisa makhluk hidup purba',
                'gambar_soal' => null
            ],
            [
                'id' => 123,
                'level' => '1',
                'pertanyaan' => 'Bagian terkecil dari suatu unsur adalah …',
                'reward_amount'=> 1200,
                'option_1' => 'Sel',
                'option_2' => 'Ion',
                'option_3' => 'Molekul',
                'option_4' => 'Atom',
                'jawaban_benar' => 'Atom',
                'gambar_soal' => null
            ],
            [
                'id' => 124,
                'level' => '1',
                'pertanyaan' => 'Tumbuhan yang bisa hidup di tempat kering disebut tumbuhan …',
                'reward_amount'=> 1200,
                'option_1' => '\( \textit{Tropofit} \)',
                'option_2' => '\( \textit{Hidrofit} \)',
                'option_3' => '\( \textit{Xerofit} \)',
                'option_4' => '\( \textit{Higrofit} \)',
                'jawaban_benar' => 'xerofit',
                'gambar_soal' => null
            ],
            [
                'id' => 125,
                'level' => '1',
                'pertanyaan' => 'Gas yang jumlahnya paling banyak di atmosfer bumi adalah …',
                'reward_amount'=> 1200,
                'option_1' => '\( \mathrm{O} \)',
                'option_2' => '\( \mathrm{H} \)',
                'option_3' => '\( \mathrm{CO_2} \)',
                'option_4' => '\( \mathrm{N} \)',
                'jawaban_benar' => 'n',
                'gambar_soal' => null
            ],
            [
                'id' => 126,
                'level' => '1',
                'pertanyaan' => 'Salah satu kota di Indonesia yang dikenal sebagai kota pelajar adalah …',
                'reward_amount'=> 1200,
                'option_1' => 'Bandung',
                'option_2' => 'Yogyakarta',
                'option_3' => 'Malang',
                'option_4' => 'Surabaya',
                'jawaban_benar' => 'Yogyakarta',
                'gambar_soal' => null
            ],
            [
                'id' => 127,
                'level' => '1',
                'pertanyaan' => 'Dalam sistem pemerintahan Indonesia, lembaga yang berwenang untuk mengadili perkara sengketa kewenangan lembaga negara adalah…',
                'reward_amount'=> 1200,
                'option_1' => 'Komisi Yudisial',
                'option_2' => 'Mahkamah Agung',
                'option_3' => 'Mahkamah Konstitusi',
                'option_4' => 'Dewan Perwakilan Rakyat',
                'jawaban_benar' => 'Mahkamah Konstitusi',
                'gambar_soal' => null
            ],
            [
                'id' => 128,
                'level' => '1',
                'pertanyaan' => 'Nama lengkap penulis novel berjudul, “Bumi Manusia” adalah …',
                'reward_amount'=> 1200,
                'option_1' => 'Pramoedya Ananta Toer',
                'option_2' => 'Andrea Hirata',
                'option_3' => 'Sapardi Djoko Damono',
                'option_4' => 'Chairil Anwar',
                'jawaban_benar' => 'Pramoedya Ananta Toer',
                'gambar_soal' => null
            ],
            [
                'id' => 129,
                'level' => '1',
                'pertanyaan' => 'Gunung yang pernah meletus dahsyat pada tahun 1815 adalah …',
                'reward_amount'=> 1200,
                'option_1' => 'Gunung Krakatau',
                'option_2' => 'Gunung Agung',
                'option_3' => 'Gunung Tambora',
                'option_4' => 'Gunung Merapi',
                'jawaban_benar' => 'Gunung Tambora',
                'gambar_soal' => null
            ],
            [
                'id' => 130,
                'level' => '1',
                'pertanyaan' => 'Alat optik yang digunakan untuk melihat benda-benda di kejauhan dengan lebih jelas adalah …',
                'reward_amount'=> 1200,
                'option_1' => 'Periskop',
                'option_2' => 'Kacamata',
                'option_3' => 'Mikroskop',
                'option_4' => 'Teleskop',
                'jawaban_benar' => 'Teleskop',
                'gambar_soal' => null
            ],
            [
                'id' => 131,
                'level' => '1',
                'pertanyaan' => 'Jenis gelombang suara yang dikeluarkan oleh paus adalah...',
                'reward_amount'=> 1200,
                'option_1' => 'Audiosonik',
                'option_2' => 'Infrasonik',
                'option_3' => 'Ultrasonik',
                'option_4' => 'Supersonik',
                'jawaban_benar' => 'Ultrasonik',
                'gambar_soal' => null
            ],
            [
                'id' => 132,
                'level' => '1',
                'pertanyaan' => 'Patung Liberty adalah simbol kebebasan yang terletak di Pulau … dan merupakan hadiah dari negara … sebagai tanda persahabatan',
                'reward_amount'=> 1200,
                'option_1' => 'Ellis - Prancis',
                'option_2' => 'Ellis - Amerika Serikat ',
                'option_3' => 'Staten - Inggris',
                'option_4' => 'Liberty - Prancis',
                'jawaban_benar' => 'Ellis - Prancis',
                'gambar_soal' => null
            ],
            [
                'id' => 133,
                'level' => '1',
                'pertanyaan' => 'Organisme yang tidak bisa menghasilkan makanannya sendiri disebut …',
                'reward_amount'=> 1200,
                'option_1' => '\( \textit{Detritivor} \)',
                'option_2' => '\( \textit{Dekomposer} \)',
                'option_3' => '\( \textit{Parasit} \) \\',
                'option_4' => '\( \textit{Heterotrof} \)',
                'jawaban_benar' => 'heterotrof',
                'gambar_soal' => null
            ],
        ]);
    }
}